#!/usr/bin/env bash

UPX_VER="upx-4.2.1-win64"

PWD=$(pwd)

BUILD_DIR="$PWD/build"
DIST_DIR="$PWD/dist"

PKG_DIR="$PWD/package"
SPEC_FILE="$PKG_DIR/windows/psmonitor.spec"

# Check for UPX
echo "Checking for UPX..."
if [ ! -d "$PKG_DIR/$UPX_VER" ]; then
  echo "Downloading UPX"
  curl -L "https://github.com/upx/upx/releases/download/v4.2.1/$UPX_VER.zip" -o "$PKG_DIR"
  unzip "$PKG_DIR/$UPX_VER.zip" -d "$PKG_DIR"
  rm -f "$PKG_DIR/$UPX_VER.zip"
else
  echo "UPX is available"
fi

# Check build dir
if [ -d "$BUILD_DIR" ]; then
  echo "Cleaning build directory..."
  rm -rf "$BUILD_DIR"
fi

# Check dist dir
if [ -d "$DIST_DIR" ]; then
  echo "Cleaning dist directory..."
  rm -rf "$DIST_DIR"
fi

echo "Building psmonitor..."
pyinstaller "$SPEC_FILE" --upx-dir "$PKG_DIR/$UPX_VER"